### ISSUE TITLE
Preserve headers from proxy

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#67] opened 2023-02-17 00:26 UTC
Make uvicorn preserve headers forwarded to it via a proxy, in particular IP address of client

**Comment by recalcitrantsupplant** [comment] 2023-04-17 02:32
review whether this is working as intended

**Comment by recalcitrantsupplant** [comment] 2023-06-23 05:59
@nicholascar we discussed in the prez dev meeting (I think after you'd left) that logging of IP addresses is best done prior to requests hitting the application. Is this still required? (The original issue w/ GSSA that brought this up was resolved by logging requests prior to Prez)

**Comment by recalcitrantsupplant** [comment] 2023-06-28 02:59
Discussed w/ Nick via chat - as above we will leave IP address logging to layers before prez.

**Closed by recalcitrantsupplant** 2023-06-28 02:59 UTC
Labels: enhancement
